name: Deploy website via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Upload site to FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: wp1094792.server-he.de
          username: ftp1094792-smb
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: /www/neobellee/
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            README.md
